# Generated by Django 4.0.1 on 2022-01-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150, unique=True)),
                ('value', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('finished', models.BooleanField(default=False, help_text='Check')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='records.client')),
                ('property', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='records.property')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
            },
        ),
    ]
