# Generated by Django 4.0.1 on 2022-01-07 20:26

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf'),
        ),
    ]
