# Generated by Django 4.0.1 on 2022-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_client_email_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
