# Generated by Django 4.0.1 on 2022-01-07 20:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
