# Generated by Django 4.0.1 on 2022-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_rent_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end',
            field=models.DateField(),
        ),
    ]
