# Generated by Django 4.0.1 on 2022-01-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
